require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'smartHome' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-camera-kit', :path => '../node_modules/react-native-camera-kit'

  target 'smartHomeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end



target 'smartHome-tvOS' do
  # Pods for smartHome-tvOS

  target 'smartHome-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
